# Generated by Django 2.2 on 2020-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200925_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
