# Generated by Django 2.2 on 2020-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_project_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienceWorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('position',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
