# Generated by Django 2.2 on 2020-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_projectsworklist_workshopsworklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsworklist',
            options={'verbose_name': 'Worklist - Project', 'verbose_name_plural': 'Worklist - Projects'},
        ),
        migrations.AlterModelOptions(
            name='workexperienceworklist',
            options={'verbose_name': 'Worklist - Work Experience', 'verbose_name_plural': 'Worklist - Work Experience'},
        ),
        migrations.AlterModelOptions(
            name='workshopsworklist',
            options={'verbose_name': 'Worklist - Workshop', 'verbose_name_plural': 'Worklist - Workshops'},
        ),
    ]
