# Generated by Django 2.2 on 2020-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20201101_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsworklist',
            options={'ordering': ('years',), 'verbose_name': 'Worklist - Project', 'verbose_name_plural': 'Worklist - Projects'},
        ),
        migrations.AlterModelOptions(
            name='workexperienceworklist',
            options={'ordering': ('years',), 'verbose_name': 'Worklist - Work Experience', 'verbose_name_plural': 'Worklist - Work Experience'},
        ),
        migrations.AlterModelOptions(
            name='workshopsworklist',
            options={'ordering': ('years',), 'verbose_name': 'Worklist - Workshop', 'verbose_name_plural': 'Worklist - Workshops'},
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
